version: '3.1'

services:
  # I remember you mentioning that you were going
  # to use MongoDB, so here it is
  explorer_trial_mongo:
    image: mongo
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
  
  # Once the API dockerfile in place
  # explorer_trial_api:
  #   build:
  #     context: ./StemExplorerApi
  #   environment:
  #     - ...
  #   ports:
  #     - "5000:5000"

  explorer_trial_ui:
    build:
      context: ./stem-explorer-ng
    environment:
      - PORT=80
      # Switch once the api service is added
      # - API_ENDPOINT=http://explorer_trial_api:5000
      - API_ENDPOINT=http://localhost:5000
    ports:
      - '4200:80'

volumes:
  mongodb-data:
    external: false
