version: '3.1'

services:
  # I remember you mentioning that you were going
  # to use MongoDB, so here it is
  explorer_trial_mongo:
    image: mongo
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

  explorer_trial_api:
    build:
      context: ./StemExplorerAPI
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - SiteHost=http://localhost:4200
      - MongoConnection=mongodb://explorer_trial_mongo:27017
    ports:
      - "5000:5000"

  explorer_trial_ui:
    build:
      context: ./stem-explorer-ng
    environment:
      - API_ENDPOINT=http://localhost:5000/api
    ports:
      - '4200:80'

volumes:
  mongodb-data:
    external: false
