version: '3.1'

services:
  # I remember you mentioning that you were going
  # to use MongoDB, so here it is
  explorer_trial_mongo:
    image: mongo
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

  explorer_trail_db:
    image: postgres:12.3
    environment:
      - POSTGRES_DB=StemExplorer
      - POSTGRES_USER=stem
      - POSTGRES_PASSWORD=stem2020
      - POSTGRES_ROOT_PASSWORD=root_password
    volumes:
      - stem-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  # To setup the database, run the following commands in the folder with StemExplorer.csproj:
  #
  # dotnet tool install --global dotnet-ef # To install the entity-framework tools
  # ConnectionStrings__StemExplorer='User ID=stem;Password=stem2020;Server=localhost;Database=StemExplorer' dotnet ef database update
  #
  # You may need to check that you do not have any other Postgres Servers running
  explorer_trial_api:
    build:
      context: ./StemExplorerAPI
    environment:
      - PORT=5000
      - ASPNETCORE_ENVIRONMENT=Development
      - SiteHost=http://localhost:4200
      - ConnectionStrings__StemExplorer=User ID=stem;Password=stem2020;Server=explorer_trail_db;Database=StemExplorer
    ports:
      - "5000:5000"
    depends_on:
      - explorer_trail_db
    links:
      - explorer_trail_db

  explorer_trial_ui:
    build:
      context: ./stem-explorer-ng
    environment:
      - PORT=4200
      - API_ENDPOINT=http://localhost:5000/api
      - AUTH_API
    ports:
      - '4200:4200'

volumes:
  mongodb-data:
    external: false
  stem-data:
    external: false
