INSERT INTO public."ChallengeCompacts"
--(Id, Title, Category, Question, Instructions, Hint, PossibleAnswers, Answer, AnswerBlurb, IsComplete, Latitude, Longitude)
VALUES
(1, 'TECT', 0, 'What is TECT?', null, 'TECT have been supporting us for the last 3 years.',
'[{"idx": 0,"label": "A Community Trust"},{"idx": 1,"label": "A Tech Company"},{"idx": 2,"label": "The name of a new car"},{"idx": 3,"label": "All of the above"}]', 0,
'Did you know that TECT provide support for local initiatives, facilities and events that bring vibrancy, connectedness, growth and economic benefits to our region. To know more visit tect.org.nz',
false),
(2, 'Trustpower', 1, 'What does Trustpower provide to our community?', null, 'One of the answer is in the name...','[{"idx": 0,"label": "Gas"},{"idx": 1,"label": "Electricity"},{"idx": 2,"label": "Internet"},{"idx": 3,"label": "All of the above"}]', 3, 'Did you know that Trustpower is based here in Tauranga? In fact their head office is just next door! To know more visit trustpower.co.nz', false),
(3, 'Xero', 1, 'Which letter in STEM does Xero cover?', null, 'Think computer...', '[{"idx": 0,"label": "Science"},{"idx": 1,"label": "Technology"},{"idx": 2,"label": "Engineering"},{"idx": 3,"label": "Mathematics"},{"idx": 4,"label": "All of the above"}]', 1, 'Xero has been supporting us since the beginning and we are so grateful to have them as a partner. Go check out their website at xero.com/nz/', false),
(4, 'Zespri', 0, 'Which fruit does Zespri sell around the world?', null, 'It can have multiple colours...', '[{"idx": 0,"label": "Apple"},{"idx": 1,"label": "Tamarillo"},{"idx": 2,"label": "Kiwifruit"},{"idx": 3,"label": "Pear"}]', 2, 'In fact they produce 6 different kinds of kiwifruit! To know more visit zespri.com', false),
(5, 'BECA', 2, 'Which STEM field does Beca cover?', null, 'Building stuff is their strength!', '[{"idx": 0,"label": "Science"},{"idx": 1,"label": "Technology"},{"idx": 2,"label": "Engineering"},{"idx": 3,"label": "Mathematics"},{"idx": 4,"label": "All of the above"}]', 2, 'Beca have just celebrated their 100 years anniversary! Go check out their website at beca.com', false),
	(6, 'Comvita', 0, 'Which animal is working hard to help Comvita making their primary resource?', null, 'They are crucial to our survival.', '[{"idx": 0,"label": "Sheep"},{"idx": 1,"label": "Bee"},{"idx": 2,"label": "Cow"}]', 1, 'Did you know that Comvita was created in 1974 and is now based in Paengaroa. To know more visit comvita.co.nz', false),
	(7, 'LawVu', 1, 'Where was the tech start up LawVu founded?', null, 'You won''t have to travel far from here to get to their office...', '[{"idx": 0,"label": "Tauranga"},{"idx": 1,"label": "Auckland"},{"idx": 2,"label": "Christchurch"},{"idx": 3,"label": "Wellington"},{"idx": 4,"label": "All of the above"}]', 0, 'LawVu is booming in New Zealand but also overseas with offices accross 6 countries. To know more visit lawvu.com', false),
	(8, 'Toi Ohomai', 1, 'Where does Toi Ohomai have campuses?', null, 'They are in more than 4 towns in New Zealand!', '[{"idx": 0,"label": "Tauranga"},{"idx": 1,"label": "Rotorua"},{"idx": 2,"label": "Whakatane"},{"idx": 3,"label": "Taupo"},{"idx": 4,"label": "Tokoroa"},{"idx": 5,"label": "All of the above"}]', 5, 'Crazy right!! To know more visit toiohomai.ac.nz', false),
	(9, 'Waikato University', 3, 'Which STEM field can you study at Waikato University?', null, 'Keep in mind that there are plenty of studies options...', '[{"idx": 0,"label": "Science"},{"idx": 1,"label": "Technology"},{"idx": 2,"label": "Engineering"},{"idx": 3,"label": "Mathematics"},{"idx": 4,"label": "All of the above"}]', 4, 'In fact it has a campus across the road from here so go check it out on your way out! To know more visit waikato.ac.nz', false);