name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -
      name: Build and push API Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stemwana/exporter-trial-api
        tags: latest
        path: ./StemExplorerAPI

    # Needs to be discussed
    # -
    #   name: Build and push UI Docker image
    #   uses: docker/build-push-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     repository: stemwana/exporter-trial-ui
    #     tags: latest
    #     path: ./stem-explorer-ng
