name: API Docker Image CI

on:
  push:
    branches:
    - master
    paths:
    - 'StemExplorerAPI/**'
    - '!*.md'
    tags:
    - '*'
  pull_request:
    branches:
    - master
    paths:
    - 'StemExplorerAPI/**'
    - '!*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and push API Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stemwana/exporter-trial-api
        path: ./StemExplorerAPI
        tag_with_ref: true
