name: UI Docker Image CI

on:
  push:
    branches:
    - master
    paths:
    - 'stem-explorer-ng/**'
    - '!*.md'
    tags:
    - '*'
  pull_request:
    branches:
    - develop
    - master
    paths:
    - 'stem-explorer-ng/**'
    - '!*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and push UI Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: stemwana/exporter-trial-ui
        path: ./stem-explorer-ng
        tag_with_ref: true
