name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        # Set the prefix up once you have an docker hub account
        IMAGE_NAME: stemwana/stemwana-youthdev
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:$(date +%s)
